-- MySQL Script generated by MySQL Workbench
-- Wed Jan  8 09:54:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema jobify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jobify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jobify` DEFAULT CHARACTER SET utf8 ;
USE `jobify` ;

-- -----------------------------------------------------
-- Table `jobify`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobify`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobify`.`vacancies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobify`.`vacancies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NULL,
  `description` VARCHAR(245) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vacancies_categories_idx` (`category_id` ASC),
  CONSTRAINT `fk_vacancies_categories`
    FOREIGN KEY (`category_id`)
    REFERENCES `jobify`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobify`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobify`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(245) NULL,
  `email` VARCHAR(245) NULL,
  `password` VARCHAR(245) NULL,
  `email_checked` TINYINT NULL,
  `created` DATETIME NULL,
  `updated` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `jobify`.`email_tokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobify`.`email_tokens` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(245) NULL,
  `valid_until` DATETIME NULL,
  `email` VARCHAR(245) NULL,
  `used` TINYINT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_email_tokens_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_email_tokens_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `jobify`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
